[package]
name = "dragonglass-model-gltf"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
gltf = { version = "0.14.0", features = [ "extras", "names" ] }
petgraph = "0.4.13"
nalgebra = "0.19.0"
nalgebra-glm = "0.5.0"